"use client";

import { useEffect, useMemo, useState } from "react";

type SearchPlayer = { player: { id: number; name: string; nationality?: string; photo?: string }; statistics?: Array<{ team?: { id: number; name: string; logo: string }; games?: { position?: string } }> };
type WatchEntry = { id: string; playerId: string; status: string; priority: number; player: { name: string; nationality?: string | null; position?: string | null; photoUrl?: string | null; currentTeam?: { name: string; logoUrl?: string | null } | null } };
const filters = [{ key: "ALL", label: "All" }, { key: "PRIORITY", label: "Priority" }, { key: "ONE_TO_WATCH", label: "One to Watch" }, { key: "WONDERKID", label: "Wonderkid" }, { key: "WATCHED", label: "Watched" }];

export default function WatchlistPage() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchPlayer[]>([]); const [entries, setEntries] = useState<WatchEntry[]>([]); const [loading, setLoading] = useState(false); const [active, setActive] = useState("ALL"); const [error, setError] = useState("");
  async function loadEntries() { const response = await fetch("/api/watchlist"); const data = await response.json(); setEntries(data.entries ?? []); }
  useEffect(() => { void loadEntries(); }, []);
  async function search() { if (query.trim().length < 2) return; setLoading(true); setError(""); try { const response = await fetch(`/api/players/search?q=${encodeURIComponent(query.trim())}`); const data = await response.json(); setResults(data.players ?? []); } catch { setError("Search failed. Check the football API configuration."); } finally { setLoading(false); } }
  async function addPlayer(player: SearchPlayer) { const response = await fetch("/api/watchlist", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ player }) }); if (!response.ok) { setError("Could not add this player."); return; } await loadEntries(); setResults([]); setQuery(""); }
  async function setStatus(playerId: string, status: string, event: React.MouseEvent) { event.preventDefault(); const response = await fetch(`/api/watchlist/${playerId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) await loadEntries(); }
  const visible = useMemo(() => active === "ALL" ? entries : entries.filter((entry) => entry.status === active), [entries, active]);
  return <main className="dashboard">
    <header className="header"><div><div className="eyebrow">Scoutboard / Player board</div><h1>Your shortlist, without the spreadsheet.</h1><p className="subtitle">Search prospects, classify them fast, and keep every viewing connected to the player.</p></div><div className="badge activeBadge">{entries.length} tracked</div></header>
    <section className="card search-card"><div className="sectionHeader"><div><div className="eyebrow">Discover</div><h2>Add a player</h2></div><span className="meta">Powered by API-Football</span></div><div className="search-row"><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void search()} placeholder="Search player name…" /><button onClick={() => void search()} disabled={loading}>{loading ? "Searching…" : "Search"}</button></div>{error && <p className="muted">{error}</p>}{results.length > 0 && <div className="results">{results.slice(0,8).map((item) => { const team=item.statistics?.find((s)=>s.team)?.team; return <button className="result" key={item.player.id} onClick={() => void addPlayer(item)}><span className="playerAvatar">{item.player.photo ? <img src={item.player.photo} alt=""/> : item.player.name.slice(0,1)}</span><span><strong>{item.player.name}</strong><small>{team?.name ?? "Club unavailable"} · {item.player.nationality ?? "Unknown"}</small></span><span className="result-action">+ Add</span></button>; })}</div>}</section>
    <section className="boardToolbar"><div className="filterGroup">{filters.map((filter)=><button key={filter.key} className={active===filter.key?"countryButton selected":"countryButton"} onClick={()=>setActive(filter.key)}>{filter.label}</button>)}</div><a className="badge" href="/calendar">Scouting calendar →</a></section>
    <section className="playerBoard">{visible.length===0?<div className="card empty"><strong>No players in this view.</strong><p>Add a prospect or change the filter.</p></div>:visible.map((entry,index)=><a className="scoutCard card" href={`/players/${entry.playerId}`} key={entry.id}><div className="cardTop"><span className="rank">{String(index+1).padStart(2,"0")}</span><span className="badge">{entry.status.replaceAll("_"," ")}</span></div><div className="scoutIdentity"><div className="scoutPhoto">{entry.player.photoUrl?<img src={entry.player.photoUrl} alt=""/>:<span>{entry.player.name.slice(0,1)}</span>}</div><div><h2>{entry.player.name}</h2><p>{entry.player.position??"Position unknown"} · {entry.player.currentTeam?.name??"Club unknown"}</p></div></div><div className="scoutTags"><button onClick={(e)=>void setStatus(entry.playerId,"PRIORITY",e)}>Priority</button><button onClick={(e)=>void setStatus(entry.playerId,"ONE_TO_WATCH",e)}>One to Watch</button><button onClick={(e)=>void setStatus(entry.playerId,"WONDERKID",e)}>Wonderkid</button></div><div className="scoutFooter"><span>{entry.player.nationality??"Nationality unknown"}</span><strong>Open workspace ↗</strong></div></a>)}</section>
  </main>;
}
